-- Seed canonical_plants with 150+ plants across all PlantCategory values.
-- Used for pg_trgm fuzzy matching in Phase 3.

INSERT INTO canonical_plants (name, category) VALUES
-- leaf (12)
('spinach',              'leaf'),
('kale',                 'leaf'),
('arugula',              'leaf'),
('bok choy',             'leaf'),
('swiss chard',          'leaf'),
('romaine lettuce',      'leaf'),
('butter lettuce',       'leaf'),
('watercress',           'leaf'),
('collard greens',       'leaf'),
('beet greens',          'leaf'),
('endive',               'leaf'),
('radicchio',            'leaf'),

-- legume (16)
('lentils',              'legume'),
('chickpeas',            'legume'),
('black beans',          'legume'),
('kidney beans',         'legume'),
('pinto beans',          'legume'),
('edamame',              'legume'),
('green peas',           'legume'),
('split peas',           'legume'),
('mung beans',           'legume'),
('navy beans',           'legume'),
('fava beans',           'legume'),
('peanuts',              'legume'),
('butter beans',         'legume'),
('soybeans',             'legume'),
('tofu',                 'legume'),
('tempeh',               'legume'),

-- nut (10)
('almonds',              'nut'),
('walnuts',              'nut'),
('cashews',              'nut'),
('pistachios',           'nut'),
('pecans',               'nut'),
('macadamia nuts',       'nut'),
('brazil nuts',          'nut'),
('hazelnuts',            'nut'),
('pine nuts',            'nut'),
('chestnuts',            'nut'),

-- seed (7)
('chia seeds',           'seed'),
('flaxseeds',            'seed'),
('sunflower seeds',      'seed'),
('pumpkin seeds',        'seed'),
('sesame seeds',         'seed'),
('hemp seeds',           'seed'),
('poppy seeds',          'seed'),

-- whole_grain (14)
('oats',                 'whole_grain'),
('quinoa',               'whole_grain'),
('brown rice',           'whole_grain'),
('barley',               'whole_grain'),
('farro',                'whole_grain'),
('buckwheat',            'whole_grain'),
('millet',               'whole_grain'),
('bulgur wheat',         'whole_grain'),
('rye',                  'whole_grain'),
('whole wheat',          'whole_grain'),
('wild rice',            'whole_grain'),
('sorghum',              'whole_grain'),
('teff',                 'whole_grain'),
('amaranth',             'whole_grain'),

-- fruit (20)
('blueberries',          'fruit'),
('strawberries',         'fruit'),
('raspberries',          'fruit'),
('blackberries',         'fruit'),
('banana',               'fruit'),
('apple',                'fruit'),
('mango',                'fruit'),
('avocado',              'fruit'),
('tomato',               'fruit'),
('orange',               'fruit'),
('lime',                 'fruit'),
('lemon',                'fruit'),
('kiwi',                 'fruit'),
('figs',                 'fruit'),
('grapes',               'fruit'),
('cherries',             'fruit'),
('pear',                 'fruit'),
('watermelon',           'fruit'),
('papaya',               'fruit'),
('dragon fruit',         'fruit'),

-- vegetable (29)
('broccoli',             'vegetable'),
('cauliflower',          'vegetable'),
('carrot',               'vegetable'),
('bell pepper',          'vegetable'),
('zucchini',             'vegetable'),
('eggplant',             'vegetable'),
('celery',               'vegetable'),
('onion',                'vegetable'),
('garlic',               'vegetable'),
('snap peas',            'vegetable'),
('green beans',          'vegetable'),
('asparagus',            'vegetable'),
('shiitake mushrooms',   'vegetable'),
('portobello mushrooms', 'vegetable'),
('bean sprouts',         'vegetable'),
('scallions',            'vegetable'),
('leek',                 'vegetable'),
('fennel',               'vegetable'),
('cabbage',              'vegetable'),
('napa cabbage',         'vegetable'),
('artichoke',            'vegetable'),
('chives',               'vegetable'),
('radish',               'vegetable'),
('daikon',               'vegetable'),
('corn',                 'vegetable'),
('okra',                 'vegetable'),
('bitter melon',         'vegetable'),
('lotus root',           'vegetable'),
('water chestnut',       'vegetable'),

-- tuber (8)
('sweet potato',         'tuber'),
('beet',                 'tuber'),
('turnip',               'tuber'),
('parsnip',              'tuber'),
('yam',                  'tuber'),
('taro',                 'tuber'),
('purple yam',           'tuber'),
('cassava',              'tuber'),

-- herb (14)
('fresh basil',          'herb'),
('fresh cilantro',       'herb'),
('fresh parsley',        'herb'),
('fresh mint',           'herb'),
('fresh dill',           'herb'),
('basil',                'herb'),
('cilantro',             'herb'),
('parsley',              'herb'),
('mint',                 'herb'),
('dill',                 'herb'),
('oregano',              'herb'),
('rosemary',             'herb'),
('sage',                 'herb'),
('tarragon',             'herb'),

-- spice (13)
('turmeric',             'spice'),
('ginger',               'spice'),
('cinnamon',             'spice'),
('cumin',                'spice'),
('black pepper',         'spice'),
('paprika',              'spice'),
('allspice',             'spice'),
('nutmeg',               'spice'),
('star anise',           'spice'),
('five-spice',           'spice'),
('sichuan pepper',       'spice'),
('coriander seed',       'spice'),
('chili flakes',         'spice'),

-- other: ZOE-counted plant compounds (coffee, tea, EVOO, dark chocolate, matcha)
('coffee',               'other'),
('green tea',            'other'),
('black tea',            'other'),
('herbal tea',           'other'),
('extra virgin olive oil','other'),
('dark chocolate',       'other'),
('matcha powder',        'other'),

-- vegetable additions from real meal logs
('cucumber',             'vegetable'),
('seaweed',              'vegetable')

ON CONFLICT (name) DO NOTHING;
